# Generated by Django 4.0.3 on 2022-05-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
